name: Dummy Action release

on:
  release:
    types:
      - published  # Trigger when a release is published

jobs:
  dummy:
    runs-on: ubuntu-latest

    steps:
    - name: Echo message
      run: echo "Build release"
      
