name: Dummy Action

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  dummy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Print the entire JSON event payload
      run: |
        # Convert the workflow_run event to JSON and print it
        echo "Workflow Run JSON Payload:"
        echo '${{ toJson(github.event.workflow_run) }}' | jq .

    - name: Extract release information
      run: |
        # Convert the workflow_run event to JSON
        release='${{ toJson(github.event.workflow_run) }}'
        
        # Extract the tag name (if available) and prerelease status
        tag_name=$(echo $release | jq -r '.head_commit.message')
        is_prerelease=$(echo $release | jq -r '.event.inputs.prerelease')

        # Output based on the release type
        if [ "$is_prerelease" = "true" ]; then
          echo "Tag: $tag_name - This is a pre-release."
        else
          echo "Tag: $tag_name - This is a release."
        fi

    - name: Echo message
      run: echo "Build release"
