name: Dummy Action

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  dummy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Print the entire JSON event payload
      run: |
        # Convert the workflow_run event to JSON and print it
        echo "Workflow Run JSON Payload:"
        echo '${{ toJson(github.event.workflow_run) }}' | jq .

    - name: Extract and print release information
      run: |
        # Convert the workflow_run event to JSON
        release='${{ toJson(github.event.workflow_run) }}'
        
        # Extract the commit message
        commit_message=$(echo $release | jq -r '.head_commit.message')
        echo "Commit Message: $commit_message"

        # Use the commit message as the tag name (if applicable)
        tag_name=$commit_message
        echo "Tag Name: $tag_name"

        # Check if the message contains "pre-release" to infer prerelease status
        if echo "$commit_message" | grep -iq "pre-release"; then
          is_prerelease="true"
        else
          is_prerelease="false"
        fi

        # Print the pre-release status
        echo "Is Pre-release: $is_prerelease"

        # Output based on the inferred release type
        if [ "$is_prerelease" = "true" ]; then
          echo "Tag: $tag_name - This is a pre-release."
        else
          echo "Tag: $tag_name - This is a release."
        fi

    - name: Echo message
      run: echo "Build release"
      
