name: Dummy Action

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  dummy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Extract release information
      run: |
        # Extract the release event payload
        release=${{ toJson(github.event.workflow_run) }}
        # Print the entire JSON payload to the console
        echo "Workflow Run JSON Payload:"
        echo $release | jq .
        echo "Workflow Run JSON Payload Done"

        # Extract the tag name from the release
        tag_name=$(echo $release | jq -r '.event.inputs.tag_name')

        # Check if it's a pre-release
        is_prerelease=$(echo $release | jq -r '.event.inputs.prerelease')

        # Output based on the release type
        if [ "$is_prerelease" = "true" ]; then
          echo "Tag: $tag_name - This is a pre-release."
        else
          echo "Tag: $tag_name - This is a release."
        fi

    - name: Echo message
      run: echo "Build release"
