name: Deployment Workflow with Manual Approval

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_deployment:
    name: Create Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Create a deployment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
              environment: 'production',
              required_contexts: [],
              auto_merge: false,
              transient_environment: true
            });
            return result.data.id;
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wait_for_approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    needs: create_deployment
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."
        env:
          DEPLOYMENT_ID: ${{ needs.create_deployment.outputs.result }}

  finalize_deployment:
    name: Finalize Deployment
    runs-on: ubuntu-latest
    needs: wait_for_approval
    steps:
      - name: Complete the deployment
        run: echo "Deployment approved, proceeding..."
        
