name: PR Workflow with Approval and Merge

on:
  pull_request:
    types: [opened, reopened]

  pull_request_review:
    types: [submitted]

  pull_request_target:
    types: [closed]

jobs:
  job1:
    name: Run Job 1 on PR Open
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    steps:
      - name: Job 1 - Initial Tasks
        run: echo "Job 1 is running on PR open"

  job2:
    name: Run Job 2 after PR Approval
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    steps:
      - name: Job 2 - After Approval
        run: echo "Job 2 is running after PR approval"

  job3:
    name: Run Job 3 on Merge
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true }}
    steps:
      - name: Job 3 - After Merge
        run: echo "Job 3 is running after PR merge"
        
