name: Create Release

on:
  push:
    branches:
      - master  # Trigger release creation when pushing to the 'main' branch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.1.${{ github.run_number }}
        release_name: Release v1.1.${{ github.run_number }}
        body: 'Automatic release created by GitHub Actions'

    - name: Upload release assets (optional)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your/asset.zip
        asset_name: asset.zip
        asset_content_type: application/zip
